# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20180220_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='post',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
